"""
Docking utility functions: ligand/receptor preparation and result parsing.

Ligand preparation: RDKit (3D generation) → meeko (PDBQT).
Receptor preparation: custom PDB → PDBQT writer for RNA.
Vina execution: vina Python package (ccsb-scripps).
"""

import os
import re
import subprocess
import tempfile
import numpy as np
from typing import Dict, List, Optional, Tuple

from rdkit import Chem
from rdkit.Chem import AllChem, rdMolDescriptors


# ─── Ligand Preparation ───────────────────────────────────────────────────────

def smiles_to_sdf(smiles: str, out_path: str, name: str = "LIG") -> bool:
    """
    Convert SMILES to 3D-optimised SDF using RDKit ETKDG.
    Returns True on success, False on failure.
    """
    mol = Chem.MolFromSmiles(smiles)
    if mol is None:
        return False

    mol = Chem.AddHs(mol)
    params = AllChem.ETKDGv3()
    params.randomSeed = 42
    result = AllChem.EmbedMolecule(mol, params)
    if result == -1:
        # Fallback: distance geometry with random coords
        result = AllChem.EmbedMolecule(mol, AllChem.EmbedParameters())
    if result == -1:
        return False

    AllChem.MMFFOptimizeMolecule(mol, maxIters=500)
    mol.SetProp("_Name", name)

    writer = Chem.SDWriter(out_path)
    writer.write(mol)
    writer.close()
    return True


def sdf_to_pdbqt_ligand(sdf_path: str, pdbqt_path: str) -> bool:
    """
    Convert SDF to PDBQT using meeko.
    meeko handles AutoDock atom-type assignment and torsion detection.
    Returns True on success.
    """
    try:
        from meeko import MoleculePreparation, PDBQTWriterLegacy

        mol = Chem.SDMolSupplier(sdf_path, removeHs=False)[0]
        if mol is None:
            return False

        preparator = MoleculePreparation()
        mol_setups = preparator.prepare(mol)
        pdbqt_string, is_ok, err = PDBQTWriterLegacy.write_string(mol_setups[0])
        if not is_ok:
            return False

        with open(pdbqt_path, "w") as fh:
            fh.write(pdbqt_string)
        return True

    except Exception as e:
        print(f"  [WARN] meeko failed ({e}); falling back to obabel")
        return _sdf_to_pdbqt_obabel(sdf_path, pdbqt_path)


def _sdf_to_pdbqt_obabel(sdf_path: str, pdbqt_path: str) -> bool:
    """Fallback: use openbabel CLI to convert SDF → PDBQT."""
    cmd = ["obabel", sdf_path, "-O", pdbqt_path, "--partialcharge", "gasteiger"]
    try:
        r = subprocess.run(cmd, capture_output=True, timeout=30)
        return r.returncode == 0 and os.path.exists(pdbqt_path)
    except (subprocess.TimeoutExpired, FileNotFoundError):
        return False


# ─── Receptor (RNA) Preparation ──────────────────────────────────────────────

# RNA-specific AutoDock atom type mapping
# Source: AutoDock4 atom types table
_RNA_ATOM_TYPES: Dict[str, str] = {
    "P":   "P",    # phosphorus
    "O5'": "OA",   # H-bond acceptor oxygen
    "O3'": "OA",
    "O4'": "OA",
    "O2'": "OA",
    "O1P": "OA",
    "O2P": "OA",
    "OP1": "OA",
    "OP2": "OA",
    "C5'": "C",
    "C4'": "C",
    "C3'": "C",
    "C2'": "C",
    "C1'": "C",
    # Adenine
    "N9":  "NA",   # H-bond acceptor
    "C8":  "A",    # aromatic C
    "N7":  "NA",
    "C5":  "A",
    "C6":  "A",
    "N6":  "N",    # H-bond donor
    "N1":  "NA",
    "C2":  "A",
    "N3":  "NA",
    "C4":  "A",
    # Guanine extras
    "O6":  "OA",
    "N2":  "N",
    # Cytosine
    "O2":  "OA",
    "N4":  "N",
    # Uracil
    "O4":  "OA",
}
_DEFAULT_RNA_TYPE = "C"


def pdb_to_pdbqt_receptor(pdb_path: str, pdbqt_path: str) -> bool:
    """
    Convert a PDB file (RNA) to PDBQT receptor format.

    Parses PDB at standard fixed-width columns (x=31-38, y=39-46, z=47-54)
    and writes a properly formatted PDBQT line with x at cols 31-38.
    Atom types assigned from _RNA_ATOM_TYPES; partial charges set to 0.000.
    """
    try:
        lines_out = ["REMARK PDBQT receptor generated by digital_selex"]
        with open(pdb_path) as fh:
            for line in fh:
                if not line.startswith(("ATOM", "HETATM")):
                    continue
                if len(line) < 54:
                    continue
                try:
                    serial    = int(line[6:11])
                    atom_name = line[12:16]           # 4 chars, keep spacing
                    resname   = line[17:20].strip()   # 3 chars, strip spaces
                    chain     = line[21:22] if len(line) > 21 else "A"
                    resnum    = int(line[22:26])
                    x         = float(line[30:38])    # standard PDB cols 31-38
                    y         = float(line[38:46])
                    z         = float(line[46:54])
                except (ValueError, IndexError):
                    continue

                ad_type = _RNA_ATOM_TYPES.get(atom_name.strip(), _DEFAULT_RNA_TYPE)

                # Write PDBQT with x at cols 31-38, charge at 71-76, type at 78-79
                pdbqt_line = (
                    f"ATOM  {serial:5d} {atom_name:<4s} {resname:<3s} "
                    f"{chain}{resnum:4d}    "
                    f"{x:8.3f}{y:8.3f}{z:8.3f}  1.00  0.00    "
                    f"{0.000:6.3f} {ad_type:<2s}"
                )
                lines_out.append(pdbqt_line)

        lines_out.append("END")
        with open(pdbqt_path, "w") as fh:
            fh.write("\n".join(lines_out) + "\n")
        return True

    except Exception as e:
        print(f"  [ERROR] pdb_to_pdbqt_receptor: {e}")
        return False


# ─── Grid Box Estimation ──────────────────────────────────────────────────────

def estimate_grid_center(pdbqt_path: str) -> Tuple[float, float, float]:
    """
    Estimate the geometric center of a receptor for grid box placement.
    Uses centroid of all heavy atoms in the PDBQT file.
    """
    coords = []
    with open(pdbqt_path) as fh:
        for line in fh:
            if line.startswith(("ATOM", "HETATM")):
                try:
                    x = float(line[30:38])
                    y = float(line[38:46])
                    z = float(line[46:54])
                    coords.append((x, y, z))
                except ValueError:
                    continue
    if not coords:
        return (0.0, 0.0, 0.0)
    arr = np.array(coords)
    return tuple(arr.mean(axis=0).tolist())


# ─── Result Parsing ───────────────────────────────────────────────────────────

def parse_vina_log(log_text: str) -> List[Dict]:
    """
    Parse AutoDock Vina output log and return list of docking modes.
    Each dict has keys: mode (int), affinity (float kcal/mol),
    rmsd_lb (float), rmsd_ub (float).
    """
    results = []
    in_table = False
    for line in log_text.splitlines():
        if "mode |   affinity" in line:
            in_table = True
            continue
        if in_table:
            line = line.strip()
            if not line or line.startswith("---") or line.startswith("Writing"):
                continue
            parts = line.split()
            if len(parts) >= 4:
                try:
                    results.append({
                        "mode":      int(parts[0]),
                        "affinity":  float(parts[1]),
                        "rmsd_lb":   float(parts[2]),
                        "rmsd_ub":   float(parts[3]),
                    })
                except ValueError:
                    continue
    return results
