#!/usr/bin/env python3
"""
Script 04 – Generate RNA 3D structures (research-grade v2).

Upgrade from v1
───────────────
Now calls structure/rna_3d.generate_rna_3d() which:
  1. Tries the RNAComposer REST API (fragment-assembly, physically realistic)
  2. Falls back to A-form coarse-grain approximation if API unavailable

Conformers: if config.structure3d.n_conformers > 1, additional conformers
are generated by applying small Gaussian coordinate perturbations (σ < 1 Å)
to the primary model.  These are labelled _c01, _c02, etc.

See structure/rna_3d.py for full scientific documentation and limitations.
"""

import argparse
import csv
import logging
import os
import sys

import numpy as np
import yaml

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
ROOT_DIR   = os.path.dirname(SCRIPT_DIR)
sys.path.insert(0, SCRIPT_DIR)
sys.path.insert(0, ROOT_DIR)

log = logging.getLogger(__name__)


def main():
    parser = argparse.ArgumentParser(description="Generate RNA 3D structures (v2)")
    parser.add_argument("--config",     default=os.path.join(ROOT_DIR, "config", "config.yaml"))
    parser.add_argument("--struct-csv", required=True, help="CSV from 03_predict_2d_structure.py")
    parser.add_argument("--outdir",     default=os.path.join(ROOT_DIR, "structures", "3d"))
    args = parser.parse_args()

    with open(args.config) as fh:
        cfg = yaml.safe_load(fh)

    os.makedirs(args.outdir, exist_ok=True)
    os.makedirs(os.path.dirname(os.path.join(ROOT_DIR, cfg["logging"]["file"])), exist_ok=True)

    logging.basicConfig(
        level=getattr(logging, cfg["logging"]["level"], logging.INFO),
        format="%(asctime)s %(levelname)s %(message)s",
        handlers=[
            logging.StreamHandler(),
            logging.FileHandler(os.path.join(ROOT_DIR, cfg["logging"]["file"]), mode="a"),
        ],
    )

    # Import upgraded 3D builder
    try:
        from structure.rna_3d import generate_rna_3d, write_conformers
        use_rna3d = True
    except ImportError as e:
        log.warning(f"structure.rna_3d import failed ({e}); using A-form fallback")
        from utils.rna_utils import build_rna_3d_approximate
        use_rna3d = False

    # Read 2D structure CSV
    rows = []
    with open(args.struct_csv) as fh:
        rows = list(csv.DictReader(fh))

    method = cfg.get("structure3d", {}).get("method", "aform_approx")
    log.info(
        f"Generating 3D structures for {len(rows)} sequences "
        f"(method={method if use_rna3d else 'aform_approx_fallback'})"
    )

    rng     = np.random.default_rng(cfg["selex"]["random_seed"])
    success = 0

    for row in rows:
        seq_id    = row["seq_id"]
        sequence  = row["sequence"]
        structure = row["structure"]

        if len(sequence) != len(structure):
            log.warning(f"  {seq_id}: length mismatch — skipped")
            continue

        if use_rna3d:
            try:
                conformers = generate_rna_3d(sequence, structure, cfg, rng)
                paths = write_conformers(conformers, seq_id, args.outdir)
                log.debug(f"  {seq_id}: {len(paths)} conformer(s) written")
                success += 1
            except Exception as e:
                log.error(f"  {seq_id}: 3D generation failed ({e}); using A-form")
                pdb_text = build_rna_3d_approximate(sequence, structure)
                out_path = os.path.join(args.outdir, f"{seq_id}.pdb")
                with open(out_path, "w") as fh:
                    fh.write(pdb_text)
                success += 1
        else:
            pdb_text = build_rna_3d_approximate(sequence, structure)
            out_path = os.path.join(args.outdir, f"{seq_id}.pdb")
            with open(out_path, "w") as fh:
                fh.write(pdb_text)
            success += 1

    log.info(f"Generated {success}/{len(rows)} 3D structures in {args.outdir}")

    if method == "aform_approx" or not use_rna3d:
        log.warning(
            "REMINDER: 3D structures are APPROXIMATE (A-form coarse-grain). "
            "Docking scores are comparative only — not absolute binding energies. "
            "Set structure3d.method=rnacomposer in config.yaml for realistic structures."
        )
    return 0


if __name__ == "__main__":
    sys.exit(main())
